// ============================================================
// records.js — HotCold USA
//
// CLIMATE_RECORDS  Historical all-time high and low temperature
//                  records keyed by "MM-DD".
//
//                  Each entry: { high: { temp, city }, low: { temp, city } }
//
//                  Used by app.js → getRecord(mmdd) to display
//                  the "Records for This Date" section.
//
//                  Note: these values are smoothed/interpolated
//                  climatological estimates, not official NWS
//                  records.  The high city transitions from
//                  Yuma, AZ (Jan–Apr, Oct–Dec) to Death Valley, CA
//                  (May–Sep) as the seasonal extreme shifts.
//                  The cold record holder is Bettles, AK year-round.
// ============================================================

const CLIMATE_RECORDS = {
  // ── JANUARY ───────────────────────────────────────────────
  "01-01": { "high": { "temp":  98, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "01-02": { "high": { "temp":  98, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "01-03": { "high": { "temp":  97, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "01-04": { "high": { "temp":  97, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "01-05": { "high": { "temp":  96, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "01-06": { "high": { "temp":  96, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "01-07": { "high": { "temp":  95, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "01-08": { "high": { "temp":  95, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "01-09": { "high": { "temp":  94, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "01-10": { "high": { "temp":  94, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "01-11": { "high": { "temp":  93, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "01-12": { "high": { "temp":  93, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-13": { "high": { "temp":  92, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-14": { "high": { "temp":  92, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-15": { "high": { "temp":  91, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-16": { "high": { "temp":  91, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-17": { "high": { "temp":  90, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-18": { "high": { "temp":  90, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-19": { "high": { "temp":  89, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "01-20": { "high": { "temp":  89, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-21": { "high": { "temp":  88, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-22": { "high": { "temp":  88, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-23": { "high": { "temp":  87, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-24": { "high": { "temp":  87, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-25": { "high": { "temp":  86, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-26": { "high": { "temp":  86, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-27": { "high": { "temp":  85, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-28": { "high": { "temp":  85, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-29": { "high": { "temp":  85, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-30": { "high": { "temp":  84, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "01-31": { "high": { "temp":  84, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },

  // ── FEBRUARY ──────────────────────────────────────────────
  "02-01": { "high": { "temp":  83, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-02": { "high": { "temp":  83, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-03": { "high": { "temp":  82, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-04": { "high": { "temp":  82, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-05": { "high": { "temp":  82, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-06": { "high": { "temp":  81, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-07": { "high": { "temp":  81, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-08": { "high": { "temp":  80, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-09": { "high": { "temp":  80, "city": "Yuma, AZ"         }, "low": { "temp": -70, "city": "Bettles, AK" } },
  "02-10": { "high": { "temp":  80, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-11": { "high": { "temp":  79, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-12": { "high": { "temp":  79, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-13": { "high": { "temp":  78, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-14": { "high": { "temp":  78, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-15": { "high": { "temp":  78, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-16": { "high": { "temp":  77, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-17": { "high": { "temp":  77, "city": "Yuma, AZ"         }, "low": { "temp": -69, "city": "Bettles, AK" } },
  "02-18": { "high": { "temp":  77, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "02-19": { "high": { "temp":  76, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "02-20": { "high": { "temp":  76, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "02-21": { "high": { "temp":  76, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "02-22": { "high": { "temp":  76, "city": "Yuma, AZ"         }, "low": { "temp": -68, "city": "Bettles, AK" } },
  "02-23": { "high": { "temp":  75, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "02-24": { "high": { "temp":  75, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "02-25": { "high": { "temp":  75, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "02-26": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "02-27": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -67, "city": "Bettles, AK" } },
  "02-28": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "02-29": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },

  // ── MARCH ─────────────────────────────────────────────────
  "03-01": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "03-02": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "03-03": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -65, "city": "Bettles, AK" } },
  "03-04": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -65, "city": "Bettles, AK" } },
  "03-05": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -65, "city": "Bettles, AK" } },
  "03-06": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -64, "city": "Bettles, AK" } },
  "03-07": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -64, "city": "Bettles, AK" } },
  "03-08": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -64, "city": "Bettles, AK" } },
  "03-09": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -63, "city": "Bettles, AK" } },
  "03-10": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -63, "city": "Bettles, AK" } },
  "03-11": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -63, "city": "Bettles, AK" } },
  "03-12": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -62, "city": "Bettles, AK" } },
  "03-13": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -62, "city": "Bettles, AK" } },
  "03-14": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -62, "city": "Bettles, AK" } },
  "03-15": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -61, "city": "Bettles, AK" } },
  "03-16": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -61, "city": "Bettles, AK" } },
  "03-17": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -61, "city": "Bettles, AK" } },
  "03-18": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -60, "city": "Bettles, AK" } },
  "03-19": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -60, "city": "Bettles, AK" } },
  "03-20": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -60, "city": "Bettles, AK" } },
  "03-21": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -59, "city": "Bettles, AK" } },
  "03-22": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -59, "city": "Bettles, AK" } },
  "03-23": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -58, "city": "Bettles, AK" } },
  "03-24": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -58, "city": "Bettles, AK" } },
  "03-25": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -58, "city": "Bettles, AK" } },
  "03-26": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -57, "city": "Bettles, AK" } },
  "03-27": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -57, "city": "Bettles, AK" } },
  "03-28": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -56, "city": "Bettles, AK" } },
  "03-29": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -56, "city": "Bettles, AK" } },
  "03-30": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -55, "city": "Bettles, AK" } },
  "03-31": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -55, "city": "Bettles, AK" } },

  // ── APRIL ─────────────────────────────────────────────────
  "04-01": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -54, "city": "Bettles, AK" } },
  "04-02": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -54, "city": "Bettles, AK" } },
  "04-03": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -54, "city": "Bettles, AK" } },
  "04-04": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -53, "city": "Bettles, AK" } },
  "04-05": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -53, "city": "Bettles, AK" } },
  "04-06": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -52, "city": "Bettles, AK" } },
  "04-07": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -52, "city": "Bettles, AK" } },
  "04-08": { "high": { "temp":  70, "city": "Yuma, AZ"         }, "low": { "temp": -51, "city": "Bettles, AK" } },
  "04-09": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -51, "city": "Bettles, AK" } },
  "04-10": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -50, "city": "Bettles, AK" } },
  "04-11": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -50, "city": "Bettles, AK" } },
  "04-12": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -49, "city": "Bettles, AK" } },
  "04-13": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -49, "city": "Bettles, AK" } },
  "04-14": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -48, "city": "Bettles, AK" } },
  "04-15": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -48, "city": "Bettles, AK" } },
  "04-16": { "high": { "temp":  71, "city": "Yuma, AZ"         }, "low": { "temp": -47, "city": "Bettles, AK" } },
  "04-17": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -47, "city": "Bettles, AK" } },
  "04-18": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -46, "city": "Bettles, AK" } },
  "04-19": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -46, "city": "Bettles, AK" } },
  "04-20": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -45, "city": "Bettles, AK" } },
  "04-21": { "high": { "temp":  72, "city": "Yuma, AZ"         }, "low": { "temp": -45, "city": "Bettles, AK" } },
  "04-22": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -44, "city": "Bettles, AK" } },
  "04-23": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -44, "city": "Bettles, AK" } },
  "04-24": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -43, "city": "Bettles, AK" } },
  "04-25": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -43, "city": "Bettles, AK" } },
  "04-26": { "high": { "temp":  73, "city": "Yuma, AZ"         }, "low": { "temp": -42, "city": "Bettles, AK" } },
  "04-27": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -42, "city": "Bettles, AK" } },
  "04-28": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -41, "city": "Bettles, AK" } },
  "04-29": { "high": { "temp":  74, "city": "Yuma, AZ"         }, "low": { "temp": -41, "city": "Bettles, AK" } },
  "04-30": { "high": { "temp":  75, "city": "Yuma, AZ"         }, "low": { "temp": -40, "city": "Bettles, AK" } },

  // ── MAY ───────────────────────────────────────────────────
  "05-01": { "high": { "temp":  75, "city": "Death Valley, CA" }, "low": { "temp": -40, "city": "Bettles, AK" } },
  "05-02": { "high": { "temp":  75, "city": "Death Valley, CA" }, "low": { "temp": -39, "city": "Bettles, AK" } },
  "05-03": { "high": { "temp":  75, "city": "Death Valley, CA" }, "low": { "temp": -39, "city": "Bettles, AK" } },
  "05-04": { "high": { "temp":  76, "city": "Death Valley, CA" }, "low": { "temp": -38, "city": "Bettles, AK" } },
  "05-05": { "high": { "temp":  76, "city": "Death Valley, CA" }, "low": { "temp": -38, "city": "Bettles, AK" } },
  "05-06": { "high": { "temp":  76, "city": "Death Valley, CA" }, "low": { "temp": -37, "city": "Bettles, AK" } },
  "05-07": { "high": { "temp":  77, "city": "Death Valley, CA" }, "low": { "temp": -37, "city": "Bettles, AK" } },
  "05-08": { "high": { "temp":  77, "city": "Death Valley, CA" }, "low": { "temp": -36, "city": "Bettles, AK" } },
  "05-09": { "high": { "temp":  77, "city": "Death Valley, CA" }, "low": { "temp": -35, "city": "Bettles, AK" } },
  "05-10": { "high": { "temp":  78, "city": "Death Valley, CA" }, "low": { "temp": -35, "city": "Bettles, AK" } },
  "05-11": { "high": { "temp":  78, "city": "Death Valley, CA" }, "low": { "temp": -34, "city": "Bettles, AK" } },
  "05-12": { "high": { "temp":  78, "city": "Death Valley, CA" }, "low": { "temp": -34, "city": "Bettles, AK" } },
  "05-13": { "high": { "temp":  79, "city": "Death Valley, CA" }, "low": { "temp": -33, "city": "Bettles, AK" } },
  "05-14": { "high": { "temp":  79, "city": "Death Valley, CA" }, "low": { "temp": -33, "city": "Bettles, AK" } },
  "05-15": { "high": { "temp":  79, "city": "Death Valley, CA" }, "low": { "temp": -32, "city": "Bettles, AK" } },
  "05-16": { "high": { "temp":  80, "city": "Death Valley, CA" }, "low": { "temp": -32, "city": "Bettles, AK" } },
  "05-17": { "high": { "temp":  80, "city": "Death Valley, CA" }, "low": { "temp": -31, "city": "Bettles, AK" } },
  "05-18": { "high": { "temp":  81, "city": "Death Valley, CA" }, "low": { "temp": -31, "city": "Bettles, AK" } },
  "05-19": { "high": { "temp":  81, "city": "Death Valley, CA" }, "low": { "temp": -30, "city": "Bettles, AK" } },
  "05-20": { "high": { "temp":  81, "city": "Death Valley, CA" }, "low": { "temp": -30, "city": "Bettles, AK" } },
  "05-21": { "high": { "temp":  82, "city": "Death Valley, CA" }, "low": { "temp": -30, "city": "Bettles, AK" } },
  "05-22": { "high": { "temp":  82, "city": "Death Valley, CA" }, "low": { "temp": -29, "city": "Bettles, AK" } },
  "05-23": { "high": { "temp":  83, "city": "Death Valley, CA" }, "low": { "temp": -29, "city": "Bettles, AK" } },
  "05-24": { "high": { "temp":  83, "city": "Death Valley, CA" }, "low": { "temp": -28, "city": "Bettles, AK" } },
  "05-25": { "high": { "temp":  83, "city": "Death Valley, CA" }, "low": { "temp": -28, "city": "Bettles, AK" } },
  "05-26": { "high": { "temp":  84, "city": "Death Valley, CA" }, "low": { "temp": -27, "city": "Bettles, AK" } },
  "05-27": { "high": { "temp":  84, "city": "Death Valley, CA" }, "low": { "temp": -27, "city": "Bettles, AK" } },
  "05-28": { "high": { "temp":  85, "city": "Death Valley, CA" }, "low": { "temp": -26, "city": "Bettles, AK" } },
  "05-29": { "high": { "temp":  85, "city": "Death Valley, CA" }, "low": { "temp": -26, "city": "Bettles, AK" } },
  "05-30": { "high": { "temp":  86, "city": "Death Valley, CA" }, "low": { "temp": -25, "city": "Bettles, AK" } },
  "05-31": { "high": { "temp":  86, "city": "Death Valley, CA" }, "low": { "temp": -25, "city": "Bettles, AK" } },

  // ── JUNE ──────────────────────────────────────────────────
  "06-01": { "high": { "temp":  87, "city": "Death Valley, CA" }, "low": { "temp": -24, "city": "Bettles, AK" } },
  "06-02": { "high": { "temp":  87, "city": "Death Valley, CA" }, "low": { "temp": -24, "city": "Bettles, AK" } },
  "06-03": { "high": { "temp":  87, "city": "Death Valley, CA" }, "low": { "temp": -24, "city": "Bettles, AK" } },
  "06-04": { "high": { "temp":  88, "city": "Death Valley, CA" }, "low": { "temp": -23, "city": "Bettles, AK" } },
  "06-05": { "high": { "temp":  88, "city": "Death Valley, CA" }, "low": { "temp": -23, "city": "Bettles, AK" } },
  "06-06": { "high": { "temp":  89, "city": "Death Valley, CA" }, "low": { "temp": -22, "city": "Bettles, AK" } },
  "06-07": { "high": { "temp":  89, "city": "Death Valley, CA" }, "low": { "temp": -22, "city": "Bettles, AK" } },
  "06-08": { "high": { "temp":  90, "city": "Death Valley, CA" }, "low": { "temp": -21, "city": "Bettles, AK" } },
  "06-09": { "high": { "temp":  90, "city": "Death Valley, CA" }, "low": { "temp": -21, "city": "Bettles, AK" } },
  "06-10": { "high": { "temp":  91, "city": "Death Valley, CA" }, "low": { "temp": -21, "city": "Bettles, AK" } },
  "06-11": { "high": { "temp":  91, "city": "Death Valley, CA" }, "low": { "temp": -20, "city": "Bettles, AK" } },
  "06-12": { "high": { "temp":  92, "city": "Death Valley, CA" }, "low": { "temp": -20, "city": "Bettles, AK" } },
  "06-13": { "high": { "temp":  92, "city": "Death Valley, CA" }, "low": { "temp": -19, "city": "Bettles, AK" } },
  "06-14": { "high": { "temp":  93, "city": "Death Valley, CA" }, "low": { "temp": -19, "city": "Bettles, AK" } },
  "06-15": { "high": { "temp":  93, "city": "Death Valley, CA" }, "low": { "temp": -19, "city": "Bettles, AK" } },
  "06-16": { "high": { "temp":  94, "city": "Death Valley, CA" }, "low": { "temp": -18, "city": "Bettles, AK" } },
  "06-17": { "high": { "temp":  94, "city": "Death Valley, CA" }, "low": { "temp": -18, "city": "Bettles, AK" } },
  "06-18": { "high": { "temp":  95, "city": "Death Valley, CA" }, "low": { "temp": -18, "city": "Bettles, AK" } },
  "06-19": { "high": { "temp":  95, "city": "Death Valley, CA" }, "low": { "temp": -17, "city": "Bettles, AK" } },
  "06-20": { "high": { "temp":  96, "city": "Death Valley, CA" }, "low": { "temp": -17, "city": "Bettles, AK" } },
  "06-21": { "high": { "temp":  96, "city": "Death Valley, CA" }, "low": { "temp": -17, "city": "Bettles, AK" } },
  "06-22": { "high": { "temp":  97, "city": "Death Valley, CA" }, "low": { "temp": -16, "city": "Bettles, AK" } },
  "06-23": { "high": { "temp":  97, "city": "Death Valley, CA" }, "low": { "temp": -16, "city": "Bettles, AK" } },
  "06-24": { "high": { "temp":  98, "city": "Death Valley, CA" }, "low": { "temp": -16, "city": "Bettles, AK" } },
  "06-25": { "high": { "temp":  98, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "06-26": { "high": { "temp":  99, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "06-27": { "high": { "temp":  99, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "06-28": { "high": { "temp": 100, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "06-29": { "high": { "temp": 101, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },
  "06-30": { "high": { "temp": 101, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },

  // ── JULY ──────────────────────────────────────────────────
  "07-01": { "high": { "temp": 102, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },
  "07-02": { "high": { "temp": 102, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },
  "07-03": { "high": { "temp": 103, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "07-04": { "high": { "temp": 103, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "07-05": { "high": { "temp": 104, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "07-06": { "high": { "temp": 104, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "07-07": { "high": { "temp": 105, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "07-08": { "high": { "temp": 105, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "07-09": { "high": { "temp": 106, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "07-10": { "high": { "temp": 106, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "07-11": { "high": { "temp": 107, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "07-12": { "high": { "temp": 107, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "07-13": { "high": { "temp": 108, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-14": { "high": { "temp": 108, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-15": { "high": { "temp": 109, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-16": { "high": { "temp": 109, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-17": { "high": { "temp": 110, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-18": { "high": { "temp": 110, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-19": { "high": { "temp": 111, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "07-20": { "high": { "temp": 111, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-21": { "high": { "temp": 112, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-22": { "high": { "temp": 112, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-23": { "high": { "temp": 113, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-24": { "high": { "temp": 113, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-25": { "high": { "temp": 113, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-26": { "high": { "temp": 114, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-27": { "high": { "temp": 114, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-28": { "high": { "temp": 115, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-29": { "high": { "temp": 115, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-30": { "high": { "temp": 116, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "07-31": { "high": { "temp": 116, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },

  // ── AUGUST ────────────────────────────────────────────────
  "08-01": { "high": { "temp": 117, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-02": { "high": { "temp": 117, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-03": { "high": { "temp": 117, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-04": { "high": { "temp": 118, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-05": { "high": { "temp": 118, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-06": { "high": { "temp": 119, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-07": { "high": { "temp": 119, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-08": { "high": { "temp": 119, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-09": { "high": { "temp": 120, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-10": { "high": { "temp": 120, "city": "Death Valley, CA" }, "low": { "temp": -10, "city": "Bettles, AK" } },
  "08-11": { "high": { "temp": 121, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-12": { "high": { "temp": 121, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-13": { "high": { "temp": 121, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-14": { "high": { "temp": 122, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-15": { "high": { "temp": 122, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-16": { "high": { "temp": 122, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-17": { "high": { "temp": 123, "city": "Death Valley, CA" }, "low": { "temp": -11, "city": "Bettles, AK" } },
  "08-18": { "high": { "temp": 123, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "08-19": { "high": { "temp": 123, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "08-20": { "high": { "temp": 124, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "08-21": { "high": { "temp": 124, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "08-22": { "high": { "temp": 124, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "08-23": { "high": { "temp": 125, "city": "Death Valley, CA" }, "low": { "temp": -12, "city": "Bettles, AK" } },
  "08-24": { "high": { "temp": 125, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "08-25": { "high": { "temp": 125, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "08-26": { "high": { "temp": 125, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "08-27": { "high": { "temp": 126, "city": "Death Valley, CA" }, "low": { "temp": -13, "city": "Bettles, AK" } },
  "08-28": { "high": { "temp": 126, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },
  "08-29": { "high": { "temp": 126, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },
  "08-30": { "high": { "temp": 127, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },
  "08-31": { "high": { "temp": 127, "city": "Death Valley, CA" }, "low": { "temp": -14, "city": "Bettles, AK" } },

  // ── SEPTEMBER ─────────────────────────────────────────────
  "09-01": { "high": { "temp": 127, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "09-02": { "high": { "temp": 127, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "09-03": { "high": { "temp": 127, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "09-04": { "high": { "temp": 128, "city": "Death Valley, CA" }, "low": { "temp": -15, "city": "Bettles, AK" } },
  "09-05": { "high": { "temp": 128, "city": "Death Valley, CA" }, "low": { "temp": -16, "city": "Bettles, AK" } },
  "09-06": { "high": { "temp": 128, "city": "Death Valley, CA" }, "low": { "temp": -16, "city": "Bettles, AK" } },
  "09-07": { "high": { "temp": 128, "city": "Death Valley, CA" }, "low": { "temp": -16, "city": "Bettles, AK" } },
  "09-08": { "high": { "temp": 128, "city": "Death Valley, CA" }, "low": { "temp": -17, "city": "Bettles, AK" } },
  "09-09": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -17, "city": "Bettles, AK" } },
  "09-10": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -17, "city": "Bettles, AK" } },
  "09-11": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -18, "city": "Bettles, AK" } },
  "09-12": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -18, "city": "Bettles, AK" } },
  "09-13": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -18, "city": "Bettles, AK" } },
  "09-14": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -19, "city": "Bettles, AK" } },
  "09-15": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -19, "city": "Bettles, AK" } },
  "09-16": { "high": { "temp": 129, "city": "Death Valley, CA" }, "low": { "temp": -19, "city": "Bettles, AK" } },
  "09-17": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -20, "city": "Bettles, AK" } },
  "09-18": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -20, "city": "Bettles, AK" } },
  "09-19": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -21, "city": "Bettles, AK" } },
  "09-20": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -21, "city": "Bettles, AK" } },
  "09-21": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -21, "city": "Bettles, AK" } },
  "09-22": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -22, "city": "Bettles, AK" } },
  "09-23": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -22, "city": "Bettles, AK" } },
  "09-24": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -23, "city": "Bettles, AK" } },
  "09-25": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -23, "city": "Bettles, AK" } },
  "09-26": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -24, "city": "Bettles, AK" } },
  "09-27": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -24, "city": "Bettles, AK" } },
  "09-28": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -24, "city": "Bettles, AK" } },
  "09-29": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -25, "city": "Bettles, AK" } },
  "09-30": { "high": { "temp": 130, "city": "Death Valley, CA" }, "low": { "temp": -25, "city": "Bettles, AK" } },

  // ── OCTOBER ───────────────────────────────────────────────
  "10-01": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -26, "city": "Bettles, AK" } },
  "10-02": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -26, "city": "Bettles, AK" } },
  "10-03": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -27, "city": "Bettles, AK" } },
  "10-04": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -27, "city": "Bettles, AK" } },
  "10-05": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -28, "city": "Bettles, AK" } },
  "10-06": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -28, "city": "Bettles, AK" } },
  "10-07": { "high": { "temp": 130, "city": "Yuma, AZ"         }, "low": { "temp": -29, "city": "Bettles, AK" } },
  "10-08": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -29, "city": "Bettles, AK" } },
  "10-09": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -30, "city": "Bettles, AK" } },
  "10-10": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -30, "city": "Bettles, AK" } },
  "10-11": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -30, "city": "Bettles, AK" } },
  "10-12": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -31, "city": "Bettles, AK" } },
  "10-13": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -31, "city": "Bettles, AK" } },
  "10-14": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -32, "city": "Bettles, AK" } },
  "10-15": { "high": { "temp": 129, "city": "Yuma, AZ"         }, "low": { "temp": -32, "city": "Bettles, AK" } },
  "10-16": { "high": { "temp": 128, "city": "Yuma, AZ"         }, "low": { "temp": -33, "city": "Bettles, AK" } },
  "10-17": { "high": { "temp": 128, "city": "Yuma, AZ"         }, "low": { "temp": -33, "city": "Bettles, AK" } },
  "10-18": { "high": { "temp": 128, "city": "Yuma, AZ"         }, "low": { "temp": -34, "city": "Bettles, AK" } },
  "10-19": { "high": { "temp": 128, "city": "Yuma, AZ"         }, "low": { "temp": -34, "city": "Bettles, AK" } },
  "10-20": { "high": { "temp": 128, "city": "Yuma, AZ"         }, "low": { "temp": -35, "city": "Bettles, AK" } },
  "10-21": { "high": { "temp": 128, "city": "Yuma, AZ"         }, "low": { "temp": -35, "city": "Bettles, AK" } },
  "10-22": { "high": { "temp": 127, "city": "Yuma, AZ"         }, "low": { "temp": -36, "city": "Bettles, AK" } },
  "10-23": { "high": { "temp": 127, "city": "Yuma, AZ"         }, "low": { "temp": -37, "city": "Bettles, AK" } },
  "10-24": { "high": { "temp": 127, "city": "Yuma, AZ"         }, "low": { "temp": -37, "city": "Bettles, AK" } },
  "10-25": { "high": { "temp": 127, "city": "Yuma, AZ"         }, "low": { "temp": -38, "city": "Bettles, AK" } },
  "10-26": { "high": { "temp": 126, "city": "Yuma, AZ"         }, "low": { "temp": -38, "city": "Bettles, AK" } },
  "10-27": { "high": { "temp": 126, "city": "Yuma, AZ"         }, "low": { "temp": -39, "city": "Bettles, AK" } },
  "10-28": { "high": { "temp": 126, "city": "Yuma, AZ"         }, "low": { "temp": -39, "city": "Bettles, AK" } },
  "10-29": { "high": { "temp": 126, "city": "Yuma, AZ"         }, "low": { "temp": -40, "city": "Bettles, AK" } },
  "10-30": { "high": { "temp": 125, "city": "Yuma, AZ"         }, "low": { "temp": -40, "city": "Bettles, AK" } },
  "10-31": { "high": { "temp": 125, "city": "Yuma, AZ"         }, "low": { "temp": -41, "city": "Bettles, AK" } },

  // ── NOVEMBER ──────────────────────────────────────────────
  "11-01": { "high": { "temp": 125, "city": "Yuma, AZ"         }, "low": { "temp": -41, "city": "Bettles, AK" } },
  "11-02": { "high": { "temp": 124, "city": "Yuma, AZ"         }, "low": { "temp": -42, "city": "Bettles, AK" } },
  "11-03": { "high": { "temp": 124, "city": "Yuma, AZ"         }, "low": { "temp": -42, "city": "Bettles, AK" } },
  "11-04": { "high": { "temp": 124, "city": "Yuma, AZ"         }, "low": { "temp": -43, "city": "Bettles, AK" } },
  "11-05": { "high": { "temp": 124, "city": "Yuma, AZ"         }, "low": { "temp": -43, "city": "Bettles, AK" } },
  "11-06": { "high": { "temp": 123, "city": "Yuma, AZ"         }, "low": { "temp": -44, "city": "Bettles, AK" } },
  "11-07": { "high": { "temp": 123, "city": "Yuma, AZ"         }, "low": { "temp": -44, "city": "Bettles, AK" } },
  "11-08": { "high": { "temp": 123, "city": "Yuma, AZ"         }, "low": { "temp": -45, "city": "Bettles, AK" } },
  "11-09": { "high": { "temp": 122, "city": "Yuma, AZ"         }, "low": { "temp": -45, "city": "Bettles, AK" } },
  "11-10": { "high": { "temp": 122, "city": "Yuma, AZ"         }, "low": { "temp": -46, "city": "Bettles, AK" } },
  "11-11": { "high": { "temp": 122, "city": "Yuma, AZ"         }, "low": { "temp": -46, "city": "Bettles, AK" } },
  "11-12": { "high": { "temp": 121, "city": "Yuma, AZ"         }, "low": { "temp": -47, "city": "Bettles, AK" } },
  "11-13": { "high": { "temp": 121, "city": "Yuma, AZ"         }, "low": { "temp": -47, "city": "Bettles, AK" } },
  "11-14": { "high": { "temp": 120, "city": "Yuma, AZ"         }, "low": { "temp": -48, "city": "Bettles, AK" } },
  "11-15": { "high": { "temp": 120, "city": "Yuma, AZ"         }, "low": { "temp": -48, "city": "Bettles, AK" } },
  "11-16": { "high": { "temp": 120, "city": "Yuma, AZ"         }, "low": { "temp": -49, "city": "Bettles, AK" } },
  "11-17": { "high": { "temp": 119, "city": "Yuma, AZ"         }, "low": { "temp": -49, "city": "Bettles, AK" } },
  "11-18": { "high": { "temp": 119, "city": "Yuma, AZ"         }, "low": { "temp": -50, "city": "Bettles, AK" } },
  "11-19": { "high": { "temp": 118, "city": "Yuma, AZ"         }, "low": { "temp": -50, "city": "Bettles, AK" } },
  "11-20": { "high": { "temp": 118, "city": "Yuma, AZ"         }, "low": { "temp": -51, "city": "Bettles, AK" } },
  "11-21": { "high": { "temp": 118, "city": "Yuma, AZ"         }, "low": { "temp": -51, "city": "Bettles, AK" } },
  "11-22": { "high": { "temp": 117, "city": "Yuma, AZ"         }, "low": { "temp": -52, "city": "Bettles, AK" } },
  "11-23": { "high": { "temp": 117, "city": "Yuma, AZ"         }, "low": { "temp": -52, "city": "Bettles, AK" } },
  "11-24": { "high": { "temp": 116, "city": "Yuma, AZ"         }, "low": { "temp": -53, "city": "Bettles, AK" } },
  "11-25": { "high": { "temp": 116, "city": "Yuma, AZ"         }, "low": { "temp": -53, "city": "Bettles, AK" } },
  "11-26": { "high": { "temp": 115, "city": "Yuma, AZ"         }, "low": { "temp": -54, "city": "Bettles, AK" } },
  "11-27": { "high": { "temp": 115, "city": "Yuma, AZ"         }, "low": { "temp": -54, "city": "Bettles, AK" } },
  "11-28": { "high": { "temp": 115, "city": "Yuma, AZ"         }, "low": { "temp": -54, "city": "Bettles, AK" } },
  "11-29": { "high": { "temp": 114, "city": "Yuma, AZ"         }, "low": { "temp": -55, "city": "Bettles, AK" } },
  "11-30": { "high": { "temp": 114, "city": "Yuma, AZ"         }, "low": { "temp": -55, "city": "Bettles, AK" } },

  // ── DECEMBER ──────────────────────────────────────────────
  "12-01": { "high": { "temp": 113, "city": "Yuma, AZ"         }, "low": { "temp": -56, "city": "Bettles, AK" } },
  "12-02": { "high": { "temp": 113, "city": "Yuma, AZ"         }, "low": { "temp": -56, "city": "Bettles, AK" } },
  "12-03": { "high": { "temp": 112, "city": "Yuma, AZ"         }, "low": { "temp": -57, "city": "Bettles, AK" } },
  "12-04": { "high": { "temp": 112, "city": "Yuma, AZ"         }, "low": { "temp": -57, "city": "Bettles, AK" } },
  "12-05": { "high": { "temp": 111, "city": "Yuma, AZ"         }, "low": { "temp": -58, "city": "Bettles, AK" } },
  "12-06": { "high": { "temp": 111, "city": "Yuma, AZ"         }, "low": { "temp": -58, "city": "Bettles, AK" } },
  "12-07": { "high": { "temp": 110, "city": "Yuma, AZ"         }, "low": { "temp": -58, "city": "Bettles, AK" } },
  "12-08": { "high": { "temp": 110, "city": "Yuma, AZ"         }, "low": { "temp": -59, "city": "Bettles, AK" } },
  "12-09": { "high": { "temp": 109, "city": "Yuma, AZ"         }, "low": { "temp": -59, "city": "Bettles, AK" } },
  "12-10": { "high": { "temp": 109, "city": "Yuma, AZ"         }, "low": { "temp": -60, "city": "Bettles, AK" } },
  "12-11": { "high": { "temp": 108, "city": "Yuma, AZ"         }, "low": { "temp": -60, "city": "Bettles, AK" } },
  "12-12": { "high": { "temp": 108, "city": "Yuma, AZ"         }, "low": { "temp": -60, "city": "Bettles, AK" } },
  "12-13": { "high": { "temp": 107, "city": "Yuma, AZ"         }, "low": { "temp": -61, "city": "Bettles, AK" } },
  "12-14": { "high": { "temp": 107, "city": "Yuma, AZ"         }, "low": { "temp": -61, "city": "Bettles, AK" } },
  "12-15": { "high": { "temp": 106, "city": "Yuma, AZ"         }, "low": { "temp": -61, "city": "Bettles, AK" } },
  "12-16": { "high": { "temp": 106, "city": "Yuma, AZ"         }, "low": { "temp": -62, "city": "Bettles, AK" } },
  "12-17": { "high": { "temp": 105, "city": "Yuma, AZ"         }, "low": { "temp": -62, "city": "Bettles, AK" } },
  "12-18": { "high": { "temp": 105, "city": "Yuma, AZ"         }, "low": { "temp": -62, "city": "Bettles, AK" } },
  "12-19": { "high": { "temp": 104, "city": "Yuma, AZ"         }, "low": { "temp": -63, "city": "Bettles, AK" } },
  "12-20": { "high": { "temp": 104, "city": "Yuma, AZ"         }, "low": { "temp": -63, "city": "Bettles, AK" } },
  "12-21": { "high": { "temp": 103, "city": "Yuma, AZ"         }, "low": { "temp": -63, "city": "Bettles, AK" } },
  "12-22": { "high": { "temp": 103, "city": "Yuma, AZ"         }, "low": { "temp": -64, "city": "Bettles, AK" } },
  "12-23": { "high": { "temp": 102, "city": "Yuma, AZ"         }, "low": { "temp": -64, "city": "Bettles, AK" } },
  "12-24": { "high": { "temp": 102, "city": "Yuma, AZ"         }, "low": { "temp": -64, "city": "Bettles, AK" } },
  "12-25": { "high": { "temp": 101, "city": "Yuma, AZ"         }, "low": { "temp": -65, "city": "Bettles, AK" } },
  "12-26": { "high": { "temp": 101, "city": "Yuma, AZ"         }, "low": { "temp": -65, "city": "Bettles, AK" } },
  "12-27": { "high": { "temp": 100, "city": "Yuma, AZ"         }, "low": { "temp": -65, "city": "Bettles, AK" } },
  "12-28": { "high": { "temp": 100, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "12-29": { "high": { "temp":  99, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "12-30": { "high": { "temp":  99, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
  "12-31": { "high": { "temp":  98, "city": "Yuma, AZ"         }, "low": { "temp": -66, "city": "Bettles, AK" } },
};
